version: '3'
services:
  mysql-service:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always
    container_name: mysql-container
    ports:
      - 3308:3306
    networks:
      - backend
  app-service:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: app-container
    restart: always
    depends_on:
      - mysql-service
    ports:
      - 8001:8000
    networks:
      - backend
networks:
  backend:
